### ISSUE TITLE
Polish printing and plot aesthetics

### ISSUE THREAD

**Issue by brianhill11** [nlapier2/PySensemakr#2]
Update contour plots to match R

**Comment by carloscinelli** [comment]
Eg.: contour lines should not touch the edges of the plot.

**Comment by jrfiedler** [comment]
Is this covered by the commit "[Added margin/space to top and right …](https://github.com/nlapier2/PySensemakr/commit/df30a54c1497c45f69c2e08ff85f9d64a5911e2d)"? Are other modifications needed?

**Comment by carloscinelli** [comment]
> Is this covered by the commit "[Added margin/space to top and right …](https://github.com/nlapier2/PySensemakr/commit/df30a54c1497c45f69c2e08ff85f9d64a5911e2d)"? Are other modifications needed?

Hi James, thanks, yes, this was solved already too
