### ISSUE TITLE
Write documentation using numpydoc style guide

### ISSUE THREAD

**Issue by carloscinelli** [nlapier2/PySensemakr#22]
We should have a consistent documentation style. The best I found is:

https://numpydoc.readthedocs.io/en/latest/format.html

**Comment by carloscinelli** [comment]
- [ ] Include validation checks:

https://numpydoc.readthedocs.io/en/latest/validation.html

**Comment by carloscinelli** [comment]
- [ ] include doctest
 https://docs.python.org/3/library/doctest.html

**Comment by KennyZhang-17** [comment]
Include all.
