### ISSUE TITLE
DataFrame object has no attribute 'append'

### ISSUE THREAD

**Issue by facastro99** [nlapier2/PySensemakr#38]
Hi,

I was getting "DataFrame object has no attribute 'append'" when calling smkr.Sensemakr.

So I changed (in my machine) line 290 of sensitivity_bounds.py from:
bounds = bounds.concat({'bound_label': bound_label, 'r2dz_x': r2dz_x, 'r2yz_dx': r2yz_dx}, ignore_index=True)

to:
bounds = pd.concat([bounds,pd.DataFrame({'bound_label': bound_label, 'r2dz_x': r2dz_x[j], 'r2yz_dx': r2yz_dx[j]}, index=[0])], ignore_index=True)

and now it works fine. Maybe something you may want to look at.

**Comment by carloscinelli** [comment]
Hi all, thanks for bringing this up, the github version is fixed, we should be updating the PyPI version soon.

**Comment by KennyZhang-17** [comment]
Pypi version 0.0.7 should fix this issue (updated just now).

**Comment by carloscinelli** [comment]
Thanks Kenny!
@facastro99 and @NickCH-K can you check if it's all good?

**Comment by NickCH-K** [comment]
Works great! Thank you.
