### ISSUE TITLE
Simplify model formula print

### ISSUE THREAD

**Issue by carloscinelli** [nlapier2/PySensemakr#6]
- print is currently outputting all dummies (for village, for example) which can get pretty big. Need to shorten in some way.

**Comment by jrfiedler** [comment]
Hi, I found this repo after seeing the original sensemakr paper, and I'm looking through the issues to see if there's anything I could help with.

Is this issue resolved by [this commit](https://github.com/nlapier2/PySensemakr/commit/cc00c73dd6ee268b61f82e6e81fd3ec7d725a704), "Shorten the summary print"?

**Comment by carloscinelli** [comment]
> Hi, I found this repo after seeing the original sensemakr paper, and I'm looking through the issues to see if there's anything I could help with.
> 
> Is this issue resolved by [this commit](https://github.com/nlapier2/PySensemakr/commit/cc00c73dd6ee268b61f82e6e81fd3ec7d725a704), "Shorten the summary print"?

Hi James! Thanks, yes, this issue was already resolved!
